//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 12.0
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

  // Procedures 
  // External procedures 
  // Chapter: Develop
  // Short Description: Open a new graphics window that preserves the aspect ratio of the given image. 
  public void dev_open_window_fit_image (HObject ho_Image, HTuple hv_Row, HTuple hv_Column, 
      HTuple hv_WidthLimit, HTuple hv_HeightLimit, out HTuple hv_WindowHandle)
  {




    // Local iconic variables 

    // Local control variables 

    HTuple hv_MinWidth = new HTuple(), hv_MaxWidth = new HTuple();
    HTuple hv_MinHeight = new HTuple(), hv_MaxHeight = new HTuple();
    HTuple hv_ResizeFactor = null, hv_ImageWidth = null, hv_ImageHeight = null;
    HTuple hv_TempWidth = null, hv_TempHeight = null, hv_WindowWidth = null;
    HTuple hv_WindowHeight = null;
    // Initialize local and output iconic variables 
    //This procedure opens a new graphics window and adjusts the size
    //such that it fits into the limits specified by WidthLimit
    //and HeightLimit, but also maintains the correct image aspect ratio.
    //
    //If it is impossible to match the minimum and maximum extent requirements
    //at the same time (f.e. if the image is very long but narrow),
    //the maximum value gets a higher priority,
    //
    //Parse input tuple WidthLimit
    if ((int)((new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(0))).TupleOr(
        new HTuple(hv_WidthLimit.TupleLess(0)))) != 0)
    {
      hv_MinWidth = 500;
      hv_MaxWidth = 800;
    }
    else if ((int)(new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(
        1))) != 0)
    {
      hv_MinWidth = 0;
      hv_MaxWidth = hv_WidthLimit.Clone();
    }
    else
    {
      hv_MinWidth = hv_WidthLimit[0];
      hv_MaxWidth = hv_WidthLimit[1];
    }
    //Parse input tuple HeightLimit
    if ((int)((new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(0))).TupleOr(
        new HTuple(hv_HeightLimit.TupleLess(0)))) != 0)
    {
      hv_MinHeight = 400;
      hv_MaxHeight = 600;
    }
    else if ((int)(new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(
        1))) != 0)
    {
      hv_MinHeight = 0;
      hv_MaxHeight = hv_HeightLimit.Clone();
    }
    else
    {
      hv_MinHeight = hv_HeightLimit[0];
      hv_MaxHeight = hv_HeightLimit[1];
    }
    //
    //Test, if window size has to be changed.
    hv_ResizeFactor = 1;
    HOperatorSet.GetImageSize(ho_Image, out hv_ImageWidth, out hv_ImageHeight);
    //First, expand window to the minimum extents (if necessary).
    if ((int)((new HTuple(hv_MinWidth.TupleGreater(hv_ImageWidth))).TupleOr(new HTuple(hv_MinHeight.TupleGreater(
        hv_ImageHeight)))) != 0)
    {
      hv_ResizeFactor = (((((hv_MinWidth.TupleReal())/hv_ImageWidth)).TupleConcat(
          (hv_MinHeight.TupleReal())/hv_ImageHeight))).TupleMax();
    }
    hv_TempWidth = hv_ImageWidth*hv_ResizeFactor;
    hv_TempHeight = hv_ImageHeight*hv_ResizeFactor;
    //Then, shrink window to maximum extents (if necessary).
    if ((int)((new HTuple(hv_MaxWidth.TupleLess(hv_TempWidth))).TupleOr(new HTuple(hv_MaxHeight.TupleLess(
        hv_TempHeight)))) != 0)
    {
      hv_ResizeFactor = hv_ResizeFactor*((((((hv_MaxWidth.TupleReal())/hv_TempWidth)).TupleConcat(
          (hv_MaxHeight.TupleReal())/hv_TempHeight))).TupleMin());
    }
    hv_WindowWidth = hv_ImageWidth*hv_ResizeFactor;
    hv_WindowHeight = hv_ImageHeight*hv_ResizeFactor;
    //Resize window
    HOperatorSet.SetWindowAttr("background_color","black");
    HOperatorSet.OpenWindow(hv_Row,hv_Column,hv_WindowWidth,hv_WindowHeight,0,"","",out hv_WindowHandle);
    HDevWindowStack.Push(hv_WindowHandle);
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.SetPart(HDevWindowStack.GetActive(), 0, 0, hv_ImageHeight-1, hv_ImageWidth-1);
    }

    return;
  }

  // Chapter: Develop
  // Short Description: Switch dev_update_pc, dev_update_var and dev_update_window to 'off'. 
  public void dev_update_off ()
  {

    // Initialize local and output iconic variables 
    //This procedure sets different update settings to 'off'.
    //This is useful to get the best performance and reduce overhead.
    //
    // dev_update_pc(...); only in hdevelop
    // dev_update_var(...); only in hdevelop
    // dev_update_window(...); only in hdevelop

    return;
  }

  // Chapter: Graphics / Text
  // Short Description: This procedure displays 'Click 'Run' to continue' in the lower right corner of the screen. 
  public void disp_continue_message (HTuple hv_WindowHandle, HTuple hv_Color, HTuple hv_Box)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_ContinueMessage = null, hv_Row = null;
    HTuple hv_Column = null, hv_Width = null, hv_Height = null;
    HTuple hv_Ascent = null, hv_Descent = null, hv_TextWidth = null;
    HTuple hv_TextHeight = null;
    // Initialize local and output iconic variables 
    //This procedure displays 'Press Run (F5) to continue' in the
    //lower right corner of the screen.
    //It uses the procedure disp_message.
    //
    //Input parameters:
    //WindowHandle: The window, where the text shall be displayed
    //Color: defines the text color.
    //   If set to '' or 'auto', the currently set color is used.
    //Box: If set to 'true', the text is displayed in a box.
    //
    hv_ContinueMessage = "Press Run (F5) to continue";
    HOperatorSet.GetWindowExtents(hv_WindowHandle, out hv_Row, out hv_Column, out hv_Width, 
        out hv_Height);
    HOperatorSet.GetStringExtents(hv_WindowHandle, (" "+hv_ContinueMessage)+" ", 
        out hv_Ascent, out hv_Descent, out hv_TextWidth, out hv_TextHeight);
    disp_message(hv_WindowHandle, hv_ContinueMessage, "window", (hv_Height-hv_TextHeight)-12, 
        (hv_Width-hv_TextWidth)-12, hv_Color, hv_Box);

    return;
  }

  // Chapter: Graphics / Text
  // Short Description: This procedure writes a text message. 
  public void disp_message (HTuple hv_WindowHandle, HTuple hv_String, HTuple hv_CoordSystem, 
      HTuple hv_Row, HTuple hv_Column, HTuple hv_Color, HTuple hv_Box)
  {



      // Local iconic variables 

      // Local control variables 

      HTuple hv_Red = null, hv_Green = null, hv_Blue = null;
      HTuple hv_Row1Part = null, hv_Column1Part = null, hv_Row2Part = null;
      HTuple hv_Column2Part = null, hv_RowWin = null, hv_ColumnWin = null;
      HTuple hv_WidthWin = null, hv_HeightWin = null, hv_MaxAscent = null;
      HTuple hv_MaxDescent = null, hv_MaxWidth = null, hv_MaxHeight = null;
      HTuple hv_R1 = new HTuple(), hv_C1 = new HTuple(), hv_FactorRow = new HTuple();
      HTuple hv_FactorColumn = new HTuple(), hv_UseShadow = null;
      HTuple hv_ShadowColor = null, hv_Exception = new HTuple();
      HTuple hv_Width = new HTuple(), hv_Index = new HTuple();
      HTuple hv_Ascent = new HTuple(), hv_Descent = new HTuple();
      HTuple hv_W = new HTuple(), hv_H = new HTuple(), hv_FrameHeight = new HTuple();
      HTuple hv_FrameWidth = new HTuple(), hv_R2 = new HTuple();
      HTuple hv_C2 = new HTuple(), hv_DrawMode = new HTuple();
      HTuple hv_CurrentColor = new HTuple();
      HTuple   hv_Box_COPY_INP_TMP = hv_Box.Clone();
      HTuple   hv_Color_COPY_INP_TMP = hv_Color.Clone();
      HTuple   hv_Column_COPY_INP_TMP = hv_Column.Clone();
      HTuple   hv_Row_COPY_INP_TMP = hv_Row.Clone();
      HTuple   hv_String_COPY_INP_TMP = hv_String.Clone();

      // Initialize local and output iconic variables 
    //This procedure displays text in a graphics window.
    //
    //Input parameters:
    //WindowHandle: The WindowHandle of the graphics window, where
    //   the message should be displayed
    //String: A tuple of strings containing the text message to be displayed
    //CoordSystem: If set to 'window', the text position is given
    //   with respect to the window coordinate system.
    //   If set to 'image', image coordinates are used.
    //   (This may be useful in zoomed images.)
    //Row: The row coordinate of the desired text position
    //   If set to -1, a default value of 12 is used.
    //Column: The column coordinate of the desired text position
    //   If set to -1, a default value of 12 is used.
    //Color: defines the color of the text as string.
    //   If set to [], '' or 'auto' the currently set color is used.
    //   If a tuple of strings is passed, the colors are used cyclically
    //   for each new textline.
    //Box: If Box[0] is set to 'true', the text is written within an orange box.
    //     If set to' false', no box is displayed.
    //     If set to a color string (e.g. 'white', '#FF00CC', etc.),
    //       the text is written in a box of that color.
    //     An optional second value for Box (Box[1]) controls if a shadow is displayed:
    //       'true' -> display a shadow in a default color
    //       'false' -> display no shadow (same as if no second value is given)
    //       otherwise -> use given string as color string for the shadow color
    //
    //Prepare window
    HOperatorSet.GetRgb(hv_WindowHandle, out hv_Red, out hv_Green, out hv_Blue);
    HOperatorSet.GetPart(hv_WindowHandle, out hv_Row1Part, out hv_Column1Part, out hv_Row2Part, 
        out hv_Column2Part);
    HOperatorSet.GetWindowExtents(hv_WindowHandle, out hv_RowWin, out hv_ColumnWin, 
        out hv_WidthWin, out hv_HeightWin);
    HOperatorSet.SetPart(hv_WindowHandle, 0, 0, hv_HeightWin-1, hv_WidthWin-1);
    //
    //default settings
    if ((int)(new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(-1))) != 0)
    {
      hv_Row_COPY_INP_TMP = 12;
    }
    if ((int)(new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(-1))) != 0)
    {
      hv_Column_COPY_INP_TMP = 12;
    }
    if ((int)(new HTuple(hv_Color_COPY_INP_TMP.TupleEqual(new HTuple()))) != 0)
    {
      hv_Color_COPY_INP_TMP = "";
    }
    //
    hv_String_COPY_INP_TMP = (((""+hv_String_COPY_INP_TMP)+"")).TupleSplit("\n");
    //
    //Estimate extentions of text depending on font size.
    HOperatorSet.GetFontExtents(hv_WindowHandle, out hv_MaxAscent, out hv_MaxDescent, 
        out hv_MaxWidth, out hv_MaxHeight);
    if ((int)(new HTuple(hv_CoordSystem.TupleEqual("window"))) != 0)
    {
      hv_R1 = hv_Row_COPY_INP_TMP.Clone();
      hv_C1 = hv_Column_COPY_INP_TMP.Clone();
    }
    else
    {
      //Transform image to window coordinates
      hv_FactorRow = (1.0*hv_HeightWin)/((hv_Row2Part-hv_Row1Part)+1);
      hv_FactorColumn = (1.0*hv_WidthWin)/((hv_Column2Part-hv_Column1Part)+1);
      hv_R1 = ((hv_Row_COPY_INP_TMP-hv_Row1Part)+0.5)*hv_FactorRow;
      hv_C1 = ((hv_Column_COPY_INP_TMP-hv_Column1Part)+0.5)*hv_FactorColumn;
    }
    //
    //Display text box depending on text size
    hv_UseShadow = 1;
    hv_ShadowColor = "gray";
    if ((int)(new HTuple(((hv_Box_COPY_INP_TMP.TupleSelect(0))).TupleEqual("true"))) != 0)
    {
      if (hv_Box_COPY_INP_TMP == null)
        hv_Box_COPY_INP_TMP = new HTuple();
      hv_Box_COPY_INP_TMP[0] = "#fce9d4";
      hv_ShadowColor = "#f28d26";
    }
    if ((int)(new HTuple((new HTuple(hv_Box_COPY_INP_TMP.TupleLength())).TupleGreater(
        1))) != 0)
    {
      if ((int)(new HTuple(((hv_Box_COPY_INP_TMP.TupleSelect(1))).TupleEqual("true"))) != 0)
      {
        //Use default ShadowColor set above
      }
      else if ((int)(new HTuple(((hv_Box_COPY_INP_TMP.TupleSelect(1))).TupleEqual(
          "false"))) != 0)
      {
        hv_UseShadow = 0;
      }
      else
      {
        hv_ShadowColor = hv_Box_COPY_INP_TMP[1];
        //Valid color?
        try
        {
          HOperatorSet.SetColor(hv_WindowHandle, hv_Box_COPY_INP_TMP.TupleSelect(
              1));
        }
        // catch (Exception) 
        catch (HalconException HDevExpDefaultException1)
        {
          HDevExpDefaultException1.ToHTuple(out hv_Exception);
          hv_Exception = "Wrong value of control parameter Box[1] (must be a 'true', 'false', or a valid color string)";
          throw new HalconException(hv_Exception);
        }
      }
    }
    if ((int)(new HTuple(((hv_Box_COPY_INP_TMP.TupleSelect(0))).TupleNotEqual("false"))) != 0)
    {
      //Valid color?
      try
      {
        HOperatorSet.SetColor(hv_WindowHandle, hv_Box_COPY_INP_TMP.TupleSelect(0));
      }
      // catch (Exception) 
      catch (HalconException HDevExpDefaultException1)
      {
        HDevExpDefaultException1.ToHTuple(out hv_Exception);
        hv_Exception = "Wrong value of control parameter Box[0] (must be a 'true', 'false', or a valid color string)";
        throw new HalconException(hv_Exception);
      }
      //Calculate box extents
      hv_String_COPY_INP_TMP = (" "+hv_String_COPY_INP_TMP)+" ";
      hv_Width = new HTuple();
      for (hv_Index=0; (int)hv_Index<=(int)((new HTuple(hv_String_COPY_INP_TMP.TupleLength()
          ))-1); hv_Index = (int)hv_Index + 1)
      {
        HOperatorSet.GetStringExtents(hv_WindowHandle, hv_String_COPY_INP_TMP.TupleSelect(
            hv_Index), out hv_Ascent, out hv_Descent, out hv_W, out hv_H);
        hv_Width = hv_Width.TupleConcat(hv_W);
      }
      hv_FrameHeight = hv_MaxHeight*(new HTuple(hv_String_COPY_INP_TMP.TupleLength()
          ));
      hv_FrameWidth = (((new HTuple(0)).TupleConcat(hv_Width))).TupleMax();
      hv_R2 = hv_R1+hv_FrameHeight;
      hv_C2 = hv_C1+hv_FrameWidth;
      //Display rectangles
      HOperatorSet.GetDraw(hv_WindowHandle, out hv_DrawMode);
      HOperatorSet.SetDraw(hv_WindowHandle, "fill");
      //Set shadow color
      HOperatorSet.SetColor(hv_WindowHandle, hv_ShadowColor);
      if ((int)(hv_UseShadow) != 0)
      {
        HOperatorSet.DispRectangle1(hv_WindowHandle, hv_R1+1, hv_C1+1, hv_R2+1, hv_C2+1);
      }
      //Set box color
      HOperatorSet.SetColor(hv_WindowHandle, hv_Box_COPY_INP_TMP.TupleSelect(0));
      HOperatorSet.DispRectangle1(hv_WindowHandle, hv_R1, hv_C1, hv_R2, hv_C2);
      HOperatorSet.SetDraw(hv_WindowHandle, hv_DrawMode);
    }
    //Write text.
    for (hv_Index=0; (int)hv_Index<=(int)((new HTuple(hv_String_COPY_INP_TMP.TupleLength()
        ))-1); hv_Index = (int)hv_Index + 1)
    {
      hv_CurrentColor = hv_Color_COPY_INP_TMP.TupleSelect(hv_Index%(new HTuple(hv_Color_COPY_INP_TMP.TupleLength()
          )));
      if ((int)((new HTuple(hv_CurrentColor.TupleNotEqual(""))).TupleAnd(new HTuple(hv_CurrentColor.TupleNotEqual(
          "auto")))) != 0)
      {
        HOperatorSet.SetColor(hv_WindowHandle, hv_CurrentColor);
      }
      else
      {
        HOperatorSet.SetRgb(hv_WindowHandle, hv_Red, hv_Green, hv_Blue);
      }
      hv_Row_COPY_INP_TMP = hv_R1+(hv_MaxHeight*hv_Index);
      HOperatorSet.SetTposition(hv_WindowHandle, hv_Row_COPY_INP_TMP, hv_C1);
      HOperatorSet.WriteString(hv_WindowHandle, hv_String_COPY_INP_TMP.TupleSelect(
          hv_Index));
    }
    //Reset changed window settings
    HOperatorSet.SetRgb(hv_WindowHandle, hv_Red, hv_Green, hv_Blue);
    HOperatorSet.SetPart(hv_WindowHandle, hv_Row1Part, hv_Column1Part, hv_Row2Part, 
        hv_Column2Part);

    return;
  }

  // Chapter: Graphics / Text
  // Short Description: Set font independent of OS 
  public void set_display_font (HTuple hv_WindowHandle, HTuple hv_Size, HTuple hv_Font, 
      HTuple hv_Bold, HTuple hv_Slant)
  {



        // Local iconic variables 

        // Local control variables 

        HTuple hv_OS = null, hv_BufferWindowHandle = new HTuple();
        HTuple hv_Ascent = new HTuple(), hv_Descent = new HTuple();
        HTuple hv_Width = new HTuple(), hv_Height = new HTuple();
        HTuple hv_Scale = new HTuple(), hv_Exception = new HTuple();
        HTuple hv_SubFamily = new HTuple(), hv_Fonts = new HTuple();
        HTuple hv_SystemFonts = new HTuple(), hv_Guess = new HTuple();
        HTuple hv_I = new HTuple(), hv_Index = new HTuple(), hv_AllowedFontSizes = new HTuple();
        HTuple hv_Distances = new HTuple(), hv_Indices = new HTuple();
        HTuple hv_FontSelRegexp = new HTuple(), hv_FontsCourier = new HTuple();
        HTuple   hv_Bold_COPY_INP_TMP = hv_Bold.Clone();
        HTuple   hv_Font_COPY_INP_TMP = hv_Font.Clone();
        HTuple   hv_Size_COPY_INP_TMP = hv_Size.Clone();
        HTuple   hv_Slant_COPY_INP_TMP = hv_Slant.Clone();

        // Initialize local and output iconic variables 
    //This procedure sets the text font of the current window with
    //the specified attributes.
    //It is assumed that following fonts are installed on the system:
    //Windows: Courier New, Arial Times New Roman
    //Mac OS X: CourierNewPS, Arial, TimesNewRomanPS
    //Linux: courier, helvetica, times
    //Because fonts are displayed smaller on Linux than on Windows,
    //a scaling factor of 1.25 is used the get comparable results.
    //For Linux, only a limited number of font sizes is supported,
    //to get comparable results, it is recommended to use one of the
    //following sizes: 9, 11, 14, 16, 20, 27
    //(which will be mapped internally on Linux systems to 11, 14, 17, 20, 25, 34)
    //
    //Input parameters:
    //WindowHandle: The graphics window for which the font will be set
    //Size: The font size. If Size=-1, the default of 16 is used.
    //Bold: If set to 'true', a bold font is used
    //Slant: If set to 'true', a slanted font is used
    //
    HOperatorSet.GetSystem("operating_system", out hv_OS);
    // dev_get_preferences(...); only in hdevelop
    // dev_set_preferences(...); only in hdevelop
    if ((int)((new HTuple(hv_Size_COPY_INP_TMP.TupleEqual(new HTuple()))).TupleOr(
        new HTuple(hv_Size_COPY_INP_TMP.TupleEqual(-1)))) != 0)
    {
      hv_Size_COPY_INP_TMP = 16;
    }
    if ((int)(new HTuple(((hv_OS.TupleSubstr(0,2))).TupleEqual("Win"))) != 0)
    {
      //Set font on Windows systems
      try
      {
        //Check, if font scaling is switched on
        HOperatorSet.OpenWindow(0, 0, 256, 256, 0, "buffer", "", out hv_BufferWindowHandle);
        HOperatorSet.SetFont(hv_BufferWindowHandle, "-Consolas-16-*-0-*-*-1-");
        HOperatorSet.GetStringExtents(hv_BufferWindowHandle, "test_string", out hv_Ascent, 
            out hv_Descent, out hv_Width, out hv_Height);
        //Expected width is 110
        hv_Scale = 110.0/hv_Width;
        hv_Size_COPY_INP_TMP = ((hv_Size_COPY_INP_TMP*hv_Scale)).TupleInt();
        HOperatorSet.CloseWindow(hv_BufferWindowHandle);
      }
      // catch (Exception) 
      catch (HalconException HDevExpDefaultException1)
      {
        HDevExpDefaultException1.ToHTuple(out hv_Exception);
        //throw (Exception)
      }
      if ((int)((new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("Courier"))).TupleOr(
          new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("courier")))) != 0)
      {
        hv_Font_COPY_INP_TMP = "Courier New";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("mono"))) != 0)
      {
        hv_Font_COPY_INP_TMP = "Consolas";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("sans"))) != 0)
      {
        hv_Font_COPY_INP_TMP = "Arial";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("serif"))) != 0)
      {
        hv_Font_COPY_INP_TMP = "Times New Roman";
      }
      if ((int)(new HTuple(hv_Bold_COPY_INP_TMP.TupleEqual("true"))) != 0)
      {
        hv_Bold_COPY_INP_TMP = 1;
      }
      else if ((int)(new HTuple(hv_Bold_COPY_INP_TMP.TupleEqual("false"))) != 0)
      {
        hv_Bold_COPY_INP_TMP = 0;
      }
      else
      {
        hv_Exception = "Wrong value of control parameter Bold";
        throw new HalconException(hv_Exception);
      }
      if ((int)(new HTuple(hv_Slant_COPY_INP_TMP.TupleEqual("true"))) != 0)
      {
        hv_Slant_COPY_INP_TMP = 1;
      }
      else if ((int)(new HTuple(hv_Slant_COPY_INP_TMP.TupleEqual("false"))) != 0)
      {
        hv_Slant_COPY_INP_TMP = 0;
      }
      else
      {
        hv_Exception = "Wrong value of control parameter Slant";
        throw new HalconException(hv_Exception);
      }
      try
      {
        HOperatorSet.SetFont(hv_WindowHandle, ((((((("-"+hv_Font_COPY_INP_TMP)+"-")+hv_Size_COPY_INP_TMP)+"-*-")+hv_Slant_COPY_INP_TMP)+"-*-*-")+hv_Bold_COPY_INP_TMP)+"-");
      }
      // catch (Exception) 
      catch (HalconException HDevExpDefaultException1)
      {
        HDevExpDefaultException1.ToHTuple(out hv_Exception);
        //throw (Exception)
      }
    }
    else if ((int)(new HTuple(((hv_OS.TupleSubstr(0,2))).TupleEqual("Dar"))) != 0)
    {
      //Set font on Mac OS X systems. Since OS X does not have a strict naming
      //scheme for font attributes, we use tables to determine the correct font
      //name.
      hv_SubFamily = 0;
      if ((int)(new HTuple(hv_Slant_COPY_INP_TMP.TupleEqual("true"))) != 0)
      {
        hv_SubFamily = hv_SubFamily.TupleBor(1);
      }
      else if ((int)(new HTuple(hv_Slant_COPY_INP_TMP.TupleNotEqual("false"))) != 0)
      {
        hv_Exception = "Wrong value of control parameter Slant";
        throw new HalconException(hv_Exception);
      }
      if ((int)(new HTuple(hv_Bold_COPY_INP_TMP.TupleEqual("true"))) != 0)
      {
        hv_SubFamily = hv_SubFamily.TupleBor(2);
      }
      else if ((int)(new HTuple(hv_Bold_COPY_INP_TMP.TupleNotEqual("false"))) != 0)
      {
        hv_Exception = "Wrong value of control parameter Bold";
        throw new HalconException(hv_Exception);
      }
      if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("mono"))) != 0)
      {
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "Menlo-Regular";
        hv_Fonts[1] = "Menlo-Italic";
        hv_Fonts[2] = "Menlo-Bold";
        hv_Fonts[3] = "Menlo-BoldItalic";
      }
      else if ((int)((new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("Courier"))).TupleOr(
          new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("courier")))) != 0)
      {
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "CourierNewPSMT";
        hv_Fonts[1] = "CourierNewPS-ItalicMT";
        hv_Fonts[2] = "CourierNewPS-BoldMT";
        hv_Fonts[3] = "CourierNewPS-BoldItalicMT";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("sans"))) != 0)
      {
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "ArialMT";
        hv_Fonts[1] = "Arial-ItalicMT";
        hv_Fonts[2] = "Arial-BoldMT";
        hv_Fonts[3] = "Arial-BoldItalicMT";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("serif"))) != 0)
      {
        hv_Fonts = new HTuple();
        hv_Fonts[0] = "TimesNewRomanPSMT";
        hv_Fonts[1] = "TimesNewRomanPS-ItalicMT";
        hv_Fonts[2] = "TimesNewRomanPS-BoldMT";
        hv_Fonts[3] = "TimesNewRomanPS-BoldItalicMT";
      }
      else
      {
        //Attempt to figure out which of the fonts installed on the system
        //the user could have meant.
        HOperatorSet.QueryFont(hv_WindowHandle, out hv_SystemFonts);
        hv_Fonts = new HTuple();
        hv_Fonts = hv_Fonts.TupleConcat(hv_Font_COPY_INP_TMP);
        hv_Fonts = hv_Fonts.TupleConcat(hv_Font_COPY_INP_TMP);
        hv_Fonts = hv_Fonts.TupleConcat(hv_Font_COPY_INP_TMP);
        hv_Fonts = hv_Fonts.TupleConcat(hv_Font_COPY_INP_TMP);
        hv_Guess = new HTuple();
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP);
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP+"-Regular");
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP+"MT");
        for (hv_I=0; (int)hv_I<=(int)((new HTuple(hv_Guess.TupleLength()))-1); hv_I = (int)hv_I + 1)
        {
          HOperatorSet.TupleFind(hv_SystemFonts, hv_Guess.TupleSelect(hv_I), out hv_Index);
          if ((int)(new HTuple(hv_Index.TupleNotEqual(-1))) != 0)
          {
            if (hv_Fonts == null)
              hv_Fonts = new HTuple();
            hv_Fonts[0] = hv_Guess.TupleSelect(hv_I);
            break;
          }
        }
        //Guess name of slanted font
        hv_Guess = new HTuple();
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP+"-Italic");
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP+"-ItalicMT");
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP+"-Oblique");
        for (hv_I=0; (int)hv_I<=(int)((new HTuple(hv_Guess.TupleLength()))-1); hv_I = (int)hv_I + 1)
        {
          HOperatorSet.TupleFind(hv_SystemFonts, hv_Guess.TupleSelect(hv_I), out hv_Index);
          if ((int)(new HTuple(hv_Index.TupleNotEqual(-1))) != 0)
          {
            if (hv_Fonts == null)
              hv_Fonts = new HTuple();
            hv_Fonts[1] = hv_Guess.TupleSelect(hv_I);
            break;
          }
        }
        //Guess name of bold font
        hv_Guess = new HTuple();
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP+"-Bold");
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP+"-BoldMT");
        for (hv_I=0; (int)hv_I<=(int)((new HTuple(hv_Guess.TupleLength()))-1); hv_I = (int)hv_I + 1)
        {
          HOperatorSet.TupleFind(hv_SystemFonts, hv_Guess.TupleSelect(hv_I), out hv_Index);
          if ((int)(new HTuple(hv_Index.TupleNotEqual(-1))) != 0)
          {
            if (hv_Fonts == null)
              hv_Fonts = new HTuple();
            hv_Fonts[2] = hv_Guess.TupleSelect(hv_I);
            break;
          }
        }
        //Guess name of bold slanted font
        hv_Guess = new HTuple();
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP+"-BoldItalic");
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP+"-BoldItalicMT");
        hv_Guess = hv_Guess.TupleConcat(hv_Font_COPY_INP_TMP+"-BoldOblique");
        for (hv_I=0; (int)hv_I<=(int)((new HTuple(hv_Guess.TupleLength()))-1); hv_I = (int)hv_I + 1)
        {
          HOperatorSet.TupleFind(hv_SystemFonts, hv_Guess.TupleSelect(hv_I), out hv_Index);
          if ((int)(new HTuple(hv_Index.TupleNotEqual(-1))) != 0)
          {
            if (hv_Fonts == null)
              hv_Fonts = new HTuple();
            hv_Fonts[3] = hv_Guess.TupleSelect(hv_I);
            break;
          }
        }
      }
      hv_Font_COPY_INP_TMP = hv_Fonts.TupleSelect(hv_SubFamily);
      try
      {
        HOperatorSet.SetFont(hv_WindowHandle, (hv_Font_COPY_INP_TMP+"-")+hv_Size_COPY_INP_TMP);
      }
      // catch (Exception) 
      catch (HalconException HDevExpDefaultException1)
      {
        HDevExpDefaultException1.ToHTuple(out hv_Exception);
        //throw (Exception)
      }
    }
    else
    {
      //Set font for UNIX systems
      hv_Size_COPY_INP_TMP = hv_Size_COPY_INP_TMP*1.25;
      hv_AllowedFontSizes = new HTuple();
      hv_AllowedFontSizes[0] = 11;
      hv_AllowedFontSizes[1] = 14;
      hv_AllowedFontSizes[2] = 17;
      hv_AllowedFontSizes[3] = 20;
      hv_AllowedFontSizes[4] = 25;
      hv_AllowedFontSizes[5] = 34;
      if ((int)(new HTuple(((hv_AllowedFontSizes.TupleFind(hv_Size_COPY_INP_TMP))).TupleEqual(
          -1))) != 0)
      {
        hv_Distances = ((hv_AllowedFontSizes-hv_Size_COPY_INP_TMP)).TupleAbs();
        HOperatorSet.TupleSortIndex(hv_Distances, out hv_Indices);
        hv_Size_COPY_INP_TMP = hv_AllowedFontSizes.TupleSelect(hv_Indices.TupleSelect(
            0));
      }
      if ((int)((new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("mono"))).TupleOr(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual(
          "Courier")))) != 0)
      {
        hv_Font_COPY_INP_TMP = "courier";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("sans"))) != 0)
      {
        hv_Font_COPY_INP_TMP = "helvetica";
      }
      else if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("serif"))) != 0)
      {
        hv_Font_COPY_INP_TMP = "times";
      }
      if ((int)(new HTuple(hv_Bold_COPY_INP_TMP.TupleEqual("true"))) != 0)
      {
        hv_Bold_COPY_INP_TMP = "bold";
      }
      else if ((int)(new HTuple(hv_Bold_COPY_INP_TMP.TupleEqual("false"))) != 0)
      {
        hv_Bold_COPY_INP_TMP = "medium";
      }
      else
      {
        hv_Exception = "Wrong value of control parameter Bold";
        throw new HalconException(hv_Exception);
      }
      if ((int)(new HTuple(hv_Slant_COPY_INP_TMP.TupleEqual("true"))) != 0)
      {
        if ((int)(new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("times"))) != 0)
        {
          hv_Slant_COPY_INP_TMP = "i";
        }
        else
        {
          hv_Slant_COPY_INP_TMP = "o";
        }
      }
      else if ((int)(new HTuple(hv_Slant_COPY_INP_TMP.TupleEqual("false"))) != 0)
      {
        hv_Slant_COPY_INP_TMP = "r";
      }
      else
      {
        hv_Exception = "Wrong value of control parameter Slant";
        throw new HalconException(hv_Exception);
      }
      try
      {
        HOperatorSet.SetFont(hv_WindowHandle, ((((((("-adobe-"+hv_Font_COPY_INP_TMP)+"-")+hv_Bold_COPY_INP_TMP)+"-")+hv_Slant_COPY_INP_TMP)+"-normal-*-")+hv_Size_COPY_INP_TMP)+"-*-*-*-*-*-*-*");
      }
      // catch (Exception) 
      catch (HalconException HDevExpDefaultException1)
      {
        HDevExpDefaultException1.ToHTuple(out hv_Exception);
        if ((int)((new HTuple(((hv_OS.TupleSubstr(0,4))).TupleEqual("Linux"))).TupleAnd(
            new HTuple(hv_Font_COPY_INP_TMP.TupleEqual("courier")))) != 0)
        {
          HOperatorSet.QueryFont(hv_WindowHandle, out hv_Fonts);
          hv_FontSelRegexp = (("^-[^-]*-[^-]*[Cc]ourier[^-]*-"+hv_Bold_COPY_INP_TMP)+"-")+hv_Slant_COPY_INP_TMP;
          hv_FontsCourier = ((hv_Fonts.TupleRegexpSelect(hv_FontSelRegexp))).TupleRegexpMatch(
              hv_FontSelRegexp);
          if ((int)(new HTuple((new HTuple(hv_FontsCourier.TupleLength())).TupleEqual(
              0))) != 0)
          {
            hv_Exception = "Wrong font name";
            //throw (Exception)
          }
          else
          {
            try
            {
              HOperatorSet.SetFont(hv_WindowHandle, (((hv_FontsCourier.TupleSelect(
                  0))+"-normal-*-")+hv_Size_COPY_INP_TMP)+"-*-*-*-*-*-*-*");
            }
            // catch (Exception) 
            catch (HalconException HDevExpDefaultException2)
            {
              HDevExpDefaultException2.ToHTuple(out hv_Exception);
              //throw (Exception)
            }
          }
        }
        //throw (Exception)
      }
    }
    // dev_set_preferences(...); only in hdevelop

    return;
  }

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_Rectangle, ho_ImageReduced;
    HObject ho_Region, ho_ResultContour=null, ho_ContCircle=null;
    HObject ho_Contour=null, ho_Cross=null;

    // Local control variables 

    HTuple hv_WindowHandle = null, hv_Width = null;
    HTuple hv_Height = null, hv_MetrologyHandle = null, hv_LineRow1 = null;
    HTuple hv_LineColumn1 = null, hv_LineRow2 = null, hv_LineColumn2 = null;
    HTuple hv_Tolerance = null, hv_Index1 = null, hv_Rows = null;
    HTuple hv_Columns = null, hv_I = null, hv_LineParameter = new HTuple();
    HTuple hv_Angle = new HTuple(), hv_Row = new HTuple();
    HTuple hv_Column = new HTuple(), hv_IsOverlapping1 = new HTuple();
    HTuple hv_Orientation1 = new HTuple(), hv_Orientation2 = new HTuple();
    HTuple hv_MRow = new HTuple(), hv_MColumn = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_Rectangle);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_Region);
    HOperatorSet.GenEmptyObj(out ho_ResultContour);
    HOperatorSet.GenEmptyObj(out ho_ContCircle);
    HOperatorSet.GenEmptyObj(out ho_Contour);
    HOperatorSet.GenEmptyObj(out ho_Cross);
    try
    {
      //This program shows how to detect the edges of a diamond
      //with subpixel accuracy and calculate the angle between them.
      //
      //In contrast to the example measure_diamond.hdev,
      //this example uses a metrology model to measure the edges.
      //
      //First, the top of the diamond is roughly segmented
      //to align the metrology objects.
      //Then, the metrology model is applied and returns the
      //parameters of the fitted lines.
      //Finally, the angle between the two lines is computed.
      //
      //Display initializations
      dev_update_off();
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.CloseWindow(HDevWindowStack.Pop());
      }
      ho_Image.Dispose();
      HOperatorSet.ReadImage(out ho_Image, "diamond/diamond_01");
      dev_open_window_fit_image(ho_Image, 0, 0, -1, -1, out hv_WindowHandle);
      set_display_font(hv_WindowHandle, 16, "mono", "true", "false");
      HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);
      //
      //Create the metrology model data structure
      HOperatorSet.CreateMetrologyModel(out hv_MetrologyHandle);
      //The image size is set in advance to speed up the
      //first call of apply_metrology_model.
      HOperatorSet.SetMetrologyModelImageSize(hv_MetrologyHandle, hv_Width, hv_Height);
      //Define the parameters of the metrology line objects
      hv_LineRow1 = new HTuple();
      hv_LineRow1[0] = 155;
      hv_LineRow1[1] = 155;
      hv_LineColumn1 = new HTuple();
      hv_LineColumn1[0] = 400;
      hv_LineColumn1[1] = 400;
      hv_LineRow2 = new HTuple();
      hv_LineRow2[0] = 290;
      hv_LineRow2[1] = 290;
      hv_LineColumn2 = new HTuple();
      hv_LineColumn2[0] = 230;
      hv_LineColumn2[1] = 570;
      hv_Tolerance = 20;
      //
      //Create two metrology line objects and set parameters
      HOperatorSet.AddMetrologyObjectLineMeasure(hv_MetrologyHandle, hv_LineRow1, 
          hv_LineColumn1, hv_LineRow2, hv_LineColumn2, hv_Tolerance, 10, 1, 20, new HTuple(), 
          new HTuple(), out hv_Index1);
      //Create region of interest for the alignment
      ho_Rectangle.Dispose();
      HOperatorSet.GenRectangle1(out ho_Rectangle, (hv_LineRow1.TupleSelect(0))-40, 
          (hv_LineColumn1.TupleSelect(0))-50, (hv_LineRow1.TupleSelect(0))+20, (hv_LineColumn1.TupleSelect(
          0))+50);
      //Change the reference coordinate system in which the
      //metrology model is given to be situated at the top of the diamond
      ho_ImageReduced.Dispose();
      HOperatorSet.ReduceDomain(ho_Image, ho_Rectangle, out ho_ImageReduced);
      ho_Region.Dispose();
      HOperatorSet.Threshold(ho_ImageReduced, out ho_Region, 128, 255);
      HOperatorSet.GetRegionPoints(ho_Region, out hv_Rows, out hv_Columns);
      HOperatorSet.SetMetrologyModelParam(hv_MetrologyHandle, "reference_system", 
          ((((hv_Rows.TupleSelect(0))).TupleConcat(hv_Columns.TupleSelect(0)))).TupleConcat(
          0));
      //
      //Main loop
      //
      for (hv_I=1; (int)hv_I<=5; hv_I = (int)hv_I + 1)
      {
        ho_Image.Dispose();
        HOperatorSet.ReadImage(out ho_Image, "diamond/diamond_"+(hv_I.TupleString(
            "02")));
        //Roughly segment the diamond's position
        ho_ImageReduced.Dispose();
        HOperatorSet.ReduceDomain(ho_Image, ho_Rectangle, out ho_ImageReduced);
        ho_Region.Dispose();
        HOperatorSet.Threshold(ho_ImageReduced, out ho_Region, 128, 255);
        //Extract the top of the diamond
        HOperatorSet.GetRegionPoints(ho_Region, out hv_Rows, out hv_Columns);
        //
        //Use the top of the diamond to align the metrology model in
        //the current image
        //
        HOperatorSet.AlignMetrologyModel(hv_MetrologyHandle, hv_Rows.TupleSelect(
            0), hv_Columns.TupleSelect(0), 0);
        //
        //
        //Perform the measurement for both lines in one call
        //
        HOperatorSet.ApplyMetrologyModel(ho_Image, hv_MetrologyHandle);
        //
        //Access results
        //
        HOperatorSet.GetMetrologyObjectResult(hv_MetrologyHandle, "all", "all", "result_type", 
            "all_param", out hv_LineParameter);
        HOperatorSet.AngleLl(hv_LineParameter.TupleSelect(0), hv_LineParameter.TupleSelect(
            1), hv_LineParameter.TupleSelect(2), hv_LineParameter.TupleSelect(3), 
            hv_LineParameter.TupleSelect(4), hv_LineParameter.TupleSelect(5), hv_LineParameter.TupleSelect(
            6), hv_LineParameter.TupleSelect(7), out hv_Angle);
        hv_Angle = hv_Angle.TupleDeg();
        //
        //Display results
        //
        //Create line contours
        ho_ResultContour.Dispose();
        HOperatorSet.GetMetrologyObjectResultContour(out ho_ResultContour, hv_MetrologyHandle, 
            "all", "all", 1.5);
        HOperatorSet.IntersectionLines(hv_LineParameter.TupleSelect(0), hv_LineParameter.TupleSelect(
            1), hv_LineParameter.TupleSelect(2), hv_LineParameter.TupleSelect(3), 
            hv_LineParameter.TupleSelect(4), hv_LineParameter.TupleSelect(5), hv_LineParameter.TupleSelect(
            6), hv_LineParameter.TupleSelect(7), out hv_Row, out hv_Column, out hv_IsOverlapping1);
        //Calculate the orientation of the two lines
        HOperatorSet.LineOrientation(hv_LineParameter.TupleSelect(0), hv_LineParameter.TupleSelect(
            1), hv_LineParameter.TupleSelect(2), hv_LineParameter.TupleSelect(3), 
            out hv_Orientation1);
        if ((int)(new HTuple(hv_Orientation1.TupleGreater(0))) != 0)
        {
          hv_Orientation1 = hv_Orientation1-((new HTuple(180)).TupleRad());
        }
        HOperatorSet.LineOrientation(hv_LineParameter.TupleSelect(4), hv_LineParameter.TupleSelect(
            5), hv_LineParameter.TupleSelect(6), hv_LineParameter.TupleSelect(7), 
            out hv_Orientation2);
        //
        //Visualize the angle between the lines
        ho_ContCircle.Dispose();
        HOperatorSet.GenCircleContourXld(out ho_ContCircle, hv_Row, hv_Column, 100, 
            hv_Orientation1, hv_Orientation2, "positive", 1);
        //Get the used measure regions and the measured points
        //for visualization
        ho_Contour.Dispose();
        HOperatorSet.GetMetrologyObjectMeasures(out ho_Contour, hv_MetrologyHandle, 
            "all", "all", out hv_MRow, out hv_MColumn);
        ho_Cross.Dispose();
        HOperatorSet.GenCrossContourXld(out ho_Cross, hv_MRow, hv_MColumn, 6, (new HTuple(45)).TupleRad()
            );
        //Display everything
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.DispObj(ho_Image, HDevWindowStack.GetActive());
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.SetLineWidth(HDevWindowStack.GetActive(), 1);
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.SetColor(HDevWindowStack.GetActive(), "yellow");
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.DispObj(ho_Contour, HDevWindowStack.GetActive());
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.DispObj(ho_Cross, HDevWindowStack.GetActive());
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.SetLineWidth(HDevWindowStack.GetActive(), 2);
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.SetColor(HDevWindowStack.GetActive(), "green");
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.DispObj(ho_ResultContour, HDevWindowStack.GetActive());
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.SetColor(HDevWindowStack.GetActive(), "blue");
        }
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.DispObj(ho_ContCircle, HDevWindowStack.GetActive());
        }
        disp_message(hv_WindowHandle, ("Angle = "+(hv_Angle.TupleString(".5")))+"бу", 
            "window", 12, 12, "black", "true");
        if ((int)(new HTuple(hv_I.TupleLess(5))) != 0)
        {
          disp_continue_message(hv_WindowHandle, "black", "true");
        }
        // stop(); only in hdevelop
      }
      //Clean up memory
      HOperatorSet.ClearMetrologyModel(hv_MetrologyHandle);
    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_Image.Dispose();
      ho_Rectangle.Dispose();
      ho_ImageReduced.Dispose();
      ho_Region.Dispose();
      ho_ResultContour.Dispose();
      ho_ContCircle.Dispose();
      ho_Contour.Dispose();
      ho_Cross.Dispose();

      throw HDevExpDefaultException;
    }
    ho_Image.Dispose();
    ho_Rectangle.Dispose();
    ho_ImageReduced.Dispose();
    ho_Region.Dispose();
    ho_ResultContour.Dispose();
    ho_ContCircle.Dispose();
    ho_Contour.Dispose();
    ho_Cross.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

